name: Check for new OTP Release Candidate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Every hour

permissions: {}

jobs:
  get-rel-candidate:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch OTP prerelease releases
        id: set-matrix
        run: |
          release_json=$(curl -sL -H "Accept: application/vnd.github+json" https://api.github.com/repos/erlang/otp/releases | tr -d '\000-\037')
          latest_rc=$(jq -c '[.[] | select(.tag_name | test("rc"))] | .[0] | {tag_name}' <<< "$release_json")
          matrix=$(jq -c 'if . != null then {release: [.]} else {release: []} end' <<< "$latest_rc")
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  check-otp:
    needs: get-rel-candidate
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    strategy:
      matrix: ${{ fromJson(needs.get-rel-candidate.outputs.matrix) }}
    steps:
      - name: Extract tag name
        run: |
          echo "Checking tag: ${MATRIX_RELEASE_TAG_NAME}"
          echo "${MATRIX_RELEASE_TAG_NAME}" > last_seen_ver.txt
          echo "LAST_OTP=${MATRIX_RELEASE_TAG_NAME}" >> $GITHUB_ENV
        env:
          MATRIX_RELEASE_TAG_NAME: ${{ matrix.release.tag_name }}

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: version-cache
        env:
          cache-name: cached-version
        with:
          path: last_cached_ver.txt
          key: ${{ env.LAST_OTP }}

      - name: Compare with Cached Version
        id: compare-vsn
        continue-on-error: true
        run: |
          diff last_cached_ver.txt last_seen_ver.txt

      - name: Update Cached Version
        run: |
          cp last_seen_ver.txt last_cached_ver.txt

      - name: Trigger OTP Package Build
        if: ${{ steps.compare-vsn.outcome == 'failure' }}
        run: |
          OTP=$(echo "${MATRIX_RELEASE_TAG_NAME}" | cut -d'-' -f2-)
          echo "Triggering build for OTP version: $OTP"
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/grisp/grisp/dispatches \
            -d "{\"event_type\":\"new-otp-release\",\"client_payload\":{\"otp\":\"\\\\\\\"${OTP}\\\\\\\"\",\"unit\":false,\"integration\":true}}"
        env:
          MATRIX_RELEASE_TAG_NAME: ${{ matrix.release.tag_name }}
