name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Erlang ${{matrix.otp}} / rebar ${{matrix.rebar3}}
    permissions:
      actions: write
      contents: read
    strategy:
      matrix:
        otp: ['26', '27', '28']
        rebar3: ['3']
        # latest rebar3 versions that do not give problems with selected OTPs
        include:
          - otp: '24'
            rebar3: '3.23.0'
          - otp: '25'
            rebar3: '3.24.0'
    steps:

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        env:
          cache-name: rebar3
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ci-${{runner.os}}-${{env.cache-name}}-otp_${{matrix.otp}}-rebar_${{matrix.rebar3}}-${{hashFiles('rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}-otp_${{matrix.otp}}-rebar_${{matrix.rebar3}}
            ci-${{runner.os}}-${{env.cache-name}}-otp_${{matrix.otp}}

      - name: Compile
        run: rebar3 do clean, compile

      - name: Test
        run: rebar3 eunit

      - name: Analyze
        run: rebar3 dialyzer

      - name: ExDoc
        if: matrix.otp == '28'
        run: rebar3 ex_doc
